# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e90eaa22a96a90b50d771cd2c31ff88486acdbf752bc34f6b05ec974adf93a29d283396fa459e1606de76868213240c30f409db6f2301b9f21cfc2da715f83a2

test:
  secret_key_base: 154d91f7d36825e21110aca5bd3a72cbd616db4bf73873a04df4c18b58c2273ae0a29031be30614f186cf96cdf614cde14dd555b5672219ee3fb53265e183059

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
